"""make attendance time columns nullable

Revision ID: 7022a1dfd988
Revises: ad06c0889ac8
Create Date: 2026-04-12 15:49:23.714734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7022a1dfd988'
down_revision: Union[str, None] = 'ad06c0889ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personio_attendance', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('personio_attendance', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personio_attendance', 'end_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('personio_attendance', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
