"""initial schema

Revision ID: be7013446181
Revises: 
Create Date: 2026-04-10 17:41:30.995213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7013446181'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('upload_batch_id', sa.Integer(), nullable=False),
    sa.Column('col_a', sa.String(length=255), nullable=True),
    sa.Column('col_b', sa.String(length=255), nullable=True),
    sa.Column('col_c', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_batches')
    op.drop_table('sales_records')
    # ### end Alembic commands ###
