"""phase2 full sales schema

Revision ID: d7547428d885
Revises: be7013446181
Create Date: 2026-04-10 19:51:43.517617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7547428d885'
down_revision: Union[str, None] = 'be7013446181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_records', sa.Column('order_number', sa.String(length=50), nullable=False))
    op.add_column('sales_records', sa.Column('erp_status_flag', sa.String(length=50), nullable=True))
    op.add_column('sales_records', sa.Column('customer_id', sa.String(length=50), nullable=True))
    op.add_column('sales_records', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('sales_records', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('sales_records', sa.Column('order_type', sa.String(length=50), nullable=True))
    op.add_column('sales_records', sa.Column('order_subtype', sa.String(length=50), nullable=True))
    op.add_column('sales_records', sa.Column('complexity_group', sa.String(length=100), nullable=True))
    op.add_column('sales_records', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('sales_records', sa.Column('vv_number', sa.String(length=100), nullable=True))
    op.add_column('sales_records', sa.Column('business_area', sa.Integer(), nullable=True))
    op.add_column('sales_records', sa.Column('project_reference', sa.Text(), nullable=True))
    op.add_column('sales_records', sa.Column('delivery_address', sa.String(length=255), nullable=True))
    op.add_column('sales_records', sa.Column('delivery_city', sa.String(length=255), nullable=True))
    op.add_column('sales_records', sa.Column('manual_lock', sa.String(length=10), nullable=True))
    op.add_column('sales_records', sa.Column('responsible_person', sa.String(length=255), nullable=True))
    op.add_column('sales_records', sa.Column('free_field_1', sa.String(length=10), nullable=True))
    op.add_column('sales_records', sa.Column('free_field_2', sa.String(length=10), nullable=True))
    op.add_column('sales_records', sa.Column('remark', sa.Text(), nullable=True))
    op.add_column('sales_records', sa.Column('project_number', sa.String(length=100), nullable=True))
    op.add_column('sales_records', sa.Column('project_name', sa.String(length=255), nullable=True))
    op.add_column('sales_records', sa.Column('manual_status', sa.Integer(), nullable=True))
    op.add_column('sales_records', sa.Column('customer_lock', sa.Integer(), nullable=True))
    op.add_column('sales_records', sa.Column('material_flag', sa.String(length=50), nullable=True))
    op.add_column('sales_records', sa.Column('end_customer_comment', sa.Text(), nullable=True))
    op.add_column('sales_records', sa.Column('internal_processor_1', sa.String(length=255), nullable=True))
    op.add_column('sales_records', sa.Column('internal_processor_2', sa.String(length=255), nullable=True))
    op.add_column('sales_records', sa.Column('approval_comment_1', sa.Text(), nullable=True))
    op.add_column('sales_records', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('sales_records', sa.Column('technical_check', sa.String(length=10), nullable=True))
    op.add_column('sales_records', sa.Column('purchase_check', sa.String(length=10), nullable=True))
    op.add_column('sales_records', sa.Column('approval_comment_2', sa.Text(), nullable=True))
    op.add_column('sales_records', sa.Column('order_date', sa.Date(), nullable=True))
    op.add_column('sales_records', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('sales_records', sa.Column('requested_date', sa.Date(), nullable=True))
    op.add_column('sales_records', sa.Column('arrival_date', sa.Date(), nullable=True))
    op.add_column('sales_records', sa.Column('remaining_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('sales_records', sa.Column('total_value', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_unique_constraint(None, 'sales_records', ['order_number'])
    op.create_foreign_key(None, 'sales_records', 'upload_batches', ['upload_batch_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sales_records', 'col_c')
    op.drop_column('sales_records', 'col_a')
    op.drop_column('sales_records', 'col_b')
    op.add_column('upload_batches', sa.Column('error_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_batches', 'error_count')
    op.add_column('sales_records', sa.Column('col_b', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sales_records', sa.Column('col_a', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('sales_records', sa.Column('col_c', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales_records', type_='foreignkey')
    op.drop_constraint(None, 'sales_records', type_='unique')
    op.drop_column('sales_records', 'total_value')
    op.drop_column('sales_records', 'remaining_value')
    op.drop_column('sales_records', 'arrival_date')
    op.drop_column('sales_records', 'requested_date')
    op.drop_column('sales_records', 'delivery_date')
    op.drop_column('sales_records', 'order_date')
    op.drop_column('sales_records', 'approval_comment_2')
    op.drop_column('sales_records', 'purchase_check')
    op.drop_column('sales_records', 'technical_check')
    op.drop_column('sales_records', 'status_code')
    op.drop_column('sales_records', 'approval_comment_1')
    op.drop_column('sales_records', 'internal_processor_2')
    op.drop_column('sales_records', 'internal_processor_1')
    op.drop_column('sales_records', 'end_customer_comment')
    op.drop_column('sales_records', 'material_flag')
    op.drop_column('sales_records', 'customer_lock')
    op.drop_column('sales_records', 'manual_status')
    op.drop_column('sales_records', 'project_name')
    op.drop_column('sales_records', 'project_number')
    op.drop_column('sales_records', 'remark')
    op.drop_column('sales_records', 'free_field_2')
    op.drop_column('sales_records', 'free_field_1')
    op.drop_column('sales_records', 'responsible_person')
    op.drop_column('sales_records', 'manual_lock')
    op.drop_column('sales_records', 'delivery_city')
    op.drop_column('sales_records', 'delivery_address')
    op.drop_column('sales_records', 'project_reference')
    op.drop_column('sales_records', 'business_area')
    op.drop_column('sales_records', 'vv_number')
    op.drop_column('sales_records', 'comment')
    op.drop_column('sales_records', 'complexity_group')
    op.drop_column('sales_records', 'order_subtype')
    op.drop_column('sales_records', 'order_type')
    op.drop_column('sales_records', 'city')
    op.drop_column('sales_records', 'customer_name')
    op.drop_column('sales_records', 'customer_id')
    op.drop_column('sales_records', 'erp_status_flag')
    op.drop_column('sales_records', 'order_number')
    # ### end Alembic commands ###
