#!/usr/bin/env bash
# install.sh — first-boot setup for a fresh LumeApps deployment.
#
# Idempotent: safe to re-run. Skips any step whose output already exists.
#   1. Generates .env with random secrets if missing.
#   2. Creates bind-mount directories used by docker-compose.yml.
#   3. Brings the stack up.
#   4. After Directus seeds the Administrator role on its first boot, queries
#      the role UUID from the DB and writes it back to .env (this is the bug
#      that caused 401s after a fresh DB reset — the API's role map was keyed
#      on a stale UUID from a previous DB).
#   5. Restarts the api container so it picks up the corrected UUID.
#
# Run from the repo root:
#   ./scripts/install.sh

set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"

log() { printf '\033[1;36m[install]\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m[install]\033[0m %s\n' "$*" >&2; }

require() {
  command -v "$1" >/dev/null 2>&1 || { err "missing required command: $1"; exit 1; }
}

require docker
require openssl
require uuidgen
require python3
require curl

# ---------------------------------------------------------------------------
# 1. Generate .env
# ---------------------------------------------------------------------------
if [ -f "$ENV_FILE" ]; then
  log "$ENV_FILE exists — skipping secret generation"
else
  log "generating $ENV_FILE with fresh secrets"
  PG_PW=$(openssl rand -base64 32 | tr -d '/+=\n' | head -c 32)
  ADMIN_PW=$(openssl rand -base64 24 | tr -d '/+=\n' | head -c 24)
  DIRECTUS_KEY=$(uuidgen | tr 'A-Z' 'a-z')
  DIRECTUS_SECRET=$(openssl rand -base64 64 | tr -d '\n')
  FERNET_KEY=$(python3 -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())' 2>/dev/null \
    || python3 -c 'import base64,os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())')
  SIGNAGE_JWT=$(python3 -c 'import secrets; print(secrets.token_urlsafe(64))')

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
POSTGRES_USER=lume
POSTGRES_PASSWORD=${PG_PW}
POSTGRES_DB=lume

# Symmetric key for backend-side Fernet encryption (Personio creds, sensor secrets).
FERNET_KEY=${FERNET_KEY}

# Directus core
DIRECTUS_KEY=${DIRECTUS_KEY}
DIRECTUS_SECRET=${DIRECTUS_SECRET}
DIRECTUS_ADMIN_EMAIL=admin@example.com
DIRECTUS_ADMIN_PASSWORD=${ADMIN_PW}

# Role UUIDs. Viewer is fixed by directus/bootstrap-roles.sh.
# Administrator is filled in below after the first Directus boot.
DIRECTUS_VIEWER_ROLE_UUID=a2222222-bbbb-bbbb-bbbb-bbbbbbbbbbbb
DIRECTUS_ADMINISTRATOR_ROLE_UUID=PENDING

# HS256 signing key for signage device JWTs (separate trust domain from DIRECTUS_SECRET).
SIGNAGE_DEVICE_JWT_SECRET=${SIGNAGE_JWT}
EOF
  chmod 600 "$ENV_FILE"
  log "wrote $ENV_FILE (mode 600)"
  log "Admin email:    admin@example.com"
  log "Admin password: ${ADMIN_PW}"
  log "Save these credentials now — they are not displayed again."
fi

# ---------------------------------------------------------------------------
# 2. Bind-mount directories
# ---------------------------------------------------------------------------
log "creating bind-mount directories"
mkdir -p \
  postgres_data \
  directus_uploads directus_extensions directus_database \
  caddy_data caddy_config \
  frontend_node_modules \
  paperless_data paperless_media paperless_consume paperless_export \
  backups

# ---------------------------------------------------------------------------
# 3. Bring stack up
# ---------------------------------------------------------------------------
log "starting stack (docker compose --profile paperless up -d)"
docker compose --profile paperless up -d --build

# ---------------------------------------------------------------------------
# 4. Resolve Administrator role UUID
# ---------------------------------------------------------------------------
PG_USER=$(awk -F= '/^POSTGRES_USER=/{print $2}' "$ENV_FILE")
PG_DB=$(awk -F= '/^POSTGRES_DB=/{print $2}' "$ENV_FILE")
CURRENT_ADMIN_UUID=$(awk -F= '/^DIRECTUS_ADMINISTRATOR_ROLE_UUID=/{print $2}' "$ENV_FILE")

log "waiting for Directus to seed roles"
RESOLVED_UUID=""
for _ in $(seq 1 60); do
  RESOLVED_UUID=$(docker compose exec -T db psql -U "$PG_USER" -d "$PG_DB" -tAc \
    "SELECT id FROM directus_roles WHERE name='Administrator' LIMIT 1;" 2>/dev/null \
    | tr -d '[:space:]' || true)
  [ -n "$RESOLVED_UUID" ] && break
  sleep 2
done

if [ -z "$RESOLVED_UUID" ]; then
  err "could not read Administrator role UUID from directus_roles after 120s"
  err "check 'docker compose logs directus' and rerun this script"
  exit 1
fi

if [ "$RESOLVED_UUID" = "$CURRENT_ADMIN_UUID" ]; then
  log "DIRECTUS_ADMINISTRATOR_ROLE_UUID already correct ($RESOLVED_UUID) — skipping"
else
  log "updating DIRECTUS_ADMINISTRATOR_ROLE_UUID: $CURRENT_ADMIN_UUID -> $RESOLVED_UUID"
  # Portable in-place edit (BSD + GNU sed).
  sed "s|^DIRECTUS_ADMINISTRATOR_ROLE_UUID=.*|DIRECTUS_ADMINISTRATOR_ROLE_UUID=${RESOLVED_UUID}|" \
    "$ENV_FILE" > "${ENV_FILE}.tmp" && mv "${ENV_FILE}.tmp" "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  log "restarting api to pick up new UUID"
  docker compose up -d api
fi

# ---------------------------------------------------------------------------
# 5. Smoke check
# ---------------------------------------------------------------------------
log "waiting for api healthy"
for _ in $(seq 1 30); do
  if curl -sf http://127.0.0.1:8000/health >/dev/null 2>&1; then
    log "api: 200"
    break
  fi
  sleep 2
done

log "done. open http://localhost in a browser (or :5173 for direct vite)."
